In [46]:
import numpy as np
import pandas as pd
from linearRegression import LinearRegression
from sklearn.model_selection import train_test_split

In [47]:
df = pd.read_csv('multiple_linear_regression_dataset.csv')
df

age  experience  income
0    25           1   30450
1    30           3   35670
2    47           2   31580
3    32           5   40130
4    43          10   47830
5    51           7   41630
6    28           5   41340
7    33           4   37650
8    37           5   40250
9    39           8   45150
10   29           1   27840
11   47           9   46110
12   54           5   36720
13   51           4   34800
14   44          12   51300
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700

In [48]:
# df = df.drop('Unnamed: 0', axis=1)
df.head()

age  experience  income
0   25           1   30450
1   30           3   35670
2   47           2   31580
3   32           5   40130
4   43          10   47830

In [49]:
lr = LinearRegression()
# x = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
# y = np.array([[2], [4], [6]])

data = df.to_numpy()

X = data[:, :2]
y = data[:, 0:1] 


print(X.shape)

(20, 2)


In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)
X_test, y_test

(array([[30,  3],
        [23,  1],
        [47,  2],
        [51,  7]]),
 array([[30],
        [23],
        [47],
        [51]]))

In [51]:
lr.fit(X_train, y_train, 10)

[[47  9]
 [25  1]
 [44  9]
 [28  5]
 [51  4]
 [37 10]
 [29  1]
 [44 12]
 [37  5]
 [58 17]
 [39  8]
 [54  5]
 [33  4]
 [32  5]
 [43 10]
 [41  6]] [[47]
 [25]
 [44]
 [28]
 [51]
 [37]
 [29]
 [44]
 [37]
 [58]
 [39]
 [54]
 [33]
 [32]
 [43]
 [41]]


In [52]:
predictions = lr.predict(X_test)

X:  [[30  3]
 [23  1]
 [47  2]
 [51  7]]
x:  [30  3]


TypeError: 'numpy.int64' object is not iterable

In [ ]:
accuracy = np.mean(predictions == y_test)
print(f'Accuracy: {accuracy*100:.2f}%')